"""drop email and pass columns from command

Revision ID: 26ba0b035837
Revises: 1f0c3472c99b
Create Date: 2024-03-14 19:33:09.960348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ba0b035837'
down_revision: Union[str, None] = '1f0c3472c99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('command_email_key', 'command', type_='unique')
    op.drop_column('command', 'email')
    op.drop_column('command', 'hashed_password')
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('command', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('command', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.create_unique_constraint('command_email_key', 'command', ['email'])
    # ### end Alembic commands ###
